version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    groups:
      radix-ui:
        patterns:
          - "@radix-ui/*"
      astro:
        patterns:
          - "@astrojs/*"
          - "astro"
      dev-dependencies:
        patterns:
          - "@eslint/js"
          - "@tailwindcss/typography"
          - "@types/eslint__js"
          - "eslint"
          - "eslint-plugin-astro"
          - "prettier"
          - "prettier-plugin-astro"
          - "typescript"
          - "typescript-eslint"
      minor-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
      include: "scope"
