name: Deploy Pages Site

on: push

# env:
#   ASTRO_DB_APP_TOKEN: ${{ github.ref_name == 'main' && secrets.PROD_ASTRO_DB_APP_TOKEN || secrets.ASTRO_DB_APP_TOKEN }}
#   ASTRO_DB_REMOTE_URL: ${{ github.ref_name == 'main' && secrets.PROD_ASTRO_DB_REMOTE_URL || secrets.ASTRO_DB_REMOTE_URL }}

jobs:
  build:
    if: github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
    name: Build and Deploy to Cloudflare
    environment: cloudflare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "npm"
      - name: Install
        run: npm ci
      # - name: Update Token Placeholder
      #   run: sed -i "s/PLACEHOLDER/${ASTRO_STUDIO_APP_TOKEN}/" astro.config.mjs
      - name: Build
        run: npm run build:remote
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=site --branch ${{ github.ref_name }}
