name: Deploy Pages Site

on: push

env:
  ASTRO_STUDIO_APP_TOKEN: ${{ secrets.ASTRO_STUDIO_APP_TOKEN }}

jobs:
  build:
    name: Build and Deploy to Cloudflare
    environment: cloudflare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "npm"
      - name: Install
        run: npm install
      - name: Build on Main
        if: github.ref_name == 'main'
        run: npm run build:remote
      - name: Build on Other Branches
        if: github.ref_name != 'main'
        run: npm run build
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=site --branch ${{ github.ref_name }}
